config/routes.rb
Dnd5::Application.routes.draw do

  resources :spells do
    collection do
      get 'list'
    end
  end

  resources :skills do
    collection do
      get 'list'
    end
  end

  resources :feats do
    collection do
      get 'list'
    end
  end

  resources :armors do
    collection do
      get 'list'
    end
  end

  resources :weapons do
    collection do
      get 'list'
    end
  end

  resources :characters

  resources :domains
  resources :classifications
  resources :races
  resources :equipment

end

app/models/armor.rb
class Armor < ActiveRecord::Base
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :title,  :description,  :cost,  :armor_bonus,  :weight,  :speed,  :don,  :remove
  has_many :characters, through: :character_armors
  ###Do not edit the above 







end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :name,  :description
  has_many :scenarios, through: :campaign_scenarios
  ###Do not edit the above 







end

app/models/character.rb
class Character < ActiveRecord::Base
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :race_id,  :class_id,  :type,  :Specialty,  :background,  :eyes,  :hair,  :height,  :weight,  :speed,  :hit_dice,  :hit_points,  :initiative,  :vision,  :size,  :level,  :strength,  :constitution,  :dexterity,  :intelligence,  :wisdom,  :charisma,  :description,  :npc
  belongs_to :classification
  belongs_to :race
  has_many :weapons, through: :character_weapons
  has_many :armors, through: :character_armors
  has_many :skills, through: :character_skills
  has_many :feats, through: :character_feats
  has_many :spells, through: :character_spells
  has_many :equipment, through: :character_equipment
  has_many :scenarios, through: :scenario_characters
  ###Do not edit the above 







end

app/models/character_armor.rb
class Character_armor < ActiveRecord::Base
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :character_id,  :armor_id,  :donned
  belongs_to :armor
  belongs_to :character
  ###Do not edit the above 







end

app/models/character_feat.rb
class Character_feat < ActiveRecord::Base
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :character_id,  :feat_id
  belongs_to :character
  belongs_to :feat
  ###Do not edit the above 







end

app/models/character_skill.rb
class Character_skill < ActiveRecord::Base
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :character_id,  :skill_id
  belongs_to :character
  belongs_to :skill
  ###Do not edit the above 







end

app/models/character_spell.rb
class Character_spell < ActiveRecord::Base
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :character_id,  :spell_id,  :prepared
  belongs_to :character
  belongs_to :spell
  ###Do not edit the above 







end

app/models/classification.rb
class Classification < ActiveRecord::Base
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :title,  :description
  has_many :classification_attributes
  has_many :races, through: :characters
  has_many :spells, through: :classification_spells
  ###Do not edit the above 







end

app/models/domain.rb
class Domain < ActiveRecord::Base
  validates :name, { :presence => true }
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :name,  :description
  has_many :spells
  ###Do not edit the above 







end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :title,  :cost,  :description
  has_many :characters, through: :character_equipment
  ###Do not edit the above 









end

app/models/feat.rb
class Feat < ActiveRecord::Base
  validates :title, { :presence => true }
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :title,  :description,  :prerequisites,  :benefit
  has_many :characters, through: :character_feats
  ###Do not edit the above 







end

app/models/race.rb
class Race < ActiveRecord::Base
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :title,  :description,  :npc
  has_many :race_attributes
  has_many :classifications, through: :characters
  ###Do not edit the above 







end

app/models/race_attribute.rb
class Race_attribute < ActiveRecord::Base
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :race_id,  :title,  :description
  belongs_to :race
  ###Do not edit the above 







end

app/models/scenario.rb
class Scenario < ActiveRecord::Base
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :name,  :description
  has_many :characters, through: :scenario_characters
  has_many :campaigns, through: :campaign_scenarios
  ###Do not edit the above 







end

app/models/skill.rb
class Skill < ActiveRecord::Base
  validates :title, { :presence => true }
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :title,  :description
  has_many :characters, through: :character_skills
  ###Do not edit the above 







end

app/models/spell.rb
class Spell < ActiveRecord::Base
  validates :domain_id, { :presence => true, :numericality => { :only_integer => true, :greater_than => 0 }}
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :title,  :description,  :level,  :domain_id,  :range,  :damage,  :requirement,  :effect,  :special,  :ritual
  belongs_to :domain
  has_many :characters, through: :character_spells
  has_many :classifications, through: :classification_spells
  ###Do not edit the above 







end

app/models/weapon.rb
class Weapon < ActiveRecord::Base
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :title,  :description,  :damage,  :attack_bonus,  :damage_bonus
  has_many :characters, through: :character_weapons
  ###Do not edit the above 







end

app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController
  # GET /weapons
  # GET /weapons.json
  def index

    @weapons = Weapon.where("character_id=?", params[:character_id])
    respond_to do |format|
      format.html  { render :layout => 'sub_page_layout' if request.xhr? } # index.html.erb
      format.json { render json: @weapons }
    end
  end

  def list
    @weapons = Weapon.where("character_id=?", params[:character_id])

    respond_to do |format|
      format.html { render :layout => 'sub_page_layout' if request.xhr? } # index.html.erb
      format.json { render json: @weapons }
    end
  end

  # GET /weapons/1
  # GET /weapons/1.json
  def show
    @weapon = Weapon.find(params[:id])

    respond_to do |format|
      format.html  { render :layout => 'sub_page_layout' if request.xhr? }  # show.html.erb
      format.json { render json: @weapon }
    end
  end

  # GET /weapons/new
  # GET /weapons/new.json
  def new
    @weapon = Weapon.new
    @weapon.character_id=params[:character_id]

    respond_to do |format|
      format.html  { render :layout => 'sub_page_layout' if request.xhr? }  # new.html.erb
      format.json { render json: @weapon }
    end
  end

  # GET /weapons/1/edit
  def edit
    @weapon = Weapon.find(params[:id])
    respond_to do |format|
      format.html  { render :layout => 'sub_page_layout' if request.xhr? }  # new.html.erb
      format.json { render json: @weapon }
    end    
  end

  # POST /weapons
  # POST /weapons.json
  def create
    @weapon = Weapon.new(params[:weapon])

    respond_to do |format|
      if @weapon.save
        format.html { redirect_to @weapon, notice: 'Weapon was successfully created.' }
        format.json { render json: @weapon, status: :created, location: @weapon }
      else
        format.html { render action: "new" }
        format.json { render json: @weapon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /weapons/1
  # PUT /weapons/1.json
  def update
    @weapon = Weapon.find(params[:id])

    respond_to do |format|
      if @weapon.update_attributes(params[:weapon])
        format.html { redirect_to @weapon, notice: 'Weapon was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @weapon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weapons/1
  # DELETE /weapons/1.json
  def destroy
    @weapon = Weapon.find(params[:id])
    @weapon.destroy

    respond_to do |format|
      format.html { redirect_to weapons_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/armors_helper.rb
module ArmorsHelper
end

app/helpers/feats_helper.rb
module FeatsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/spells_helper.rb
module SpellsHelper
end

app/helpers/weapons_helper.rb
module WeaponsHelper
end

app/views/weapons/_ajax_links.html.erb
<script>
  ajaxifyClose('.closeLink','#editHolder')
  ajaxifyLink('.ajaxLink','#editHolder')
  ajaxifyDeleteLink('.ajaxDeleteLink','#editHolder')
  ajaxifySubmit('.ajaxSubmit','#editHolder')
</script>

app/views/weapons/_form.html.erb
<%= form_for(@weapon) do |f| %>
  <% if @weapon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@weapon.errors.count, "error") %> prohibited this weapon from being saved:</h2>

      <ul>
      <% @weapon.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :character_id %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, {:rows => 0, :cols => 0, :class => 'smallDescriptionArea'} %>
  </div>
  <div class="field">
    <%= f.label :damage %><br />
    <%= f.text_field :damage %>
  </div>
  <div class="field">
    <%= f.label :attack_bonus %><br />
    <%= f.number_field :attack_bonus %>
  </div>
  <div class="field">
    <%= f.label :damage_bonus %><br />
    <%= f.number_field :damage_bonus %>
  </div>
  <div class="actions">
    <%= f.submit nil, :class => 'ajaxSubmit' %>
  </div>
<% end %>

app/views/weapons/edit.html.erb
<h1>Editing weapon</h1>

<%= render 'form' %>

<%= link_to 'Show', @weapon, :class => 'ajaxLink' %> |
<%= link_to 'Back', weapons_path(:character_id => @weapon.character_id), :class => 'ajaxLink' %>

app/views/weapons/index.html.erb
<h1>Listing weapons</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Damage</th>
    <th>Attack<br/>bonus</th>
    <th>Damage<br/>bonus</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @weapons.each do |weapon| %>
  <tr>
    <td><%= weapon.title %></td>
    <td><%= weapon.damage %></td>
    <td><%= weapon.attack_bonus %></td>
    <td><%= weapon.damage_bonus %></td>
    <td><%= link_to 'Show', weapon, :class => 'ajaxLink'  %></td>
    <td><%= link_to 'Edit', edit_weapon_path(weapon), :class => 'ajaxLink' %></td>
    <td><%= link_to 'Destroy', weapon_path(weapon,:character_id => weapon.character_id), :class => 'ajaxDeleteLink' %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Weapon', new_weapon_path(:character_id => params[:character_id]), :class => 'ajaxLink' %>

app/views/weapons/list.html.erb
<h3>Weapons
  <img src="/assets/Sword-Left.svg" class="sectionSword"/></h3>

<table>
  <tr>
    <th>Title</th>
    <th>Damage</th>
    <th>Attack<br/>bonus</th>
    <th>Damage<br/>bonus</th>
  </tr>

<% @weapons.each do |weapon| %>
  <tr>
    <td><%= weapon.title %></td>
    <td><%= weapon.damage %></td>
    <td><%= weapon.attack_bonus %></td>
    <td><%= weapon.damage_bonus %></td>
  </tr>
<% end %>
</table>

app/views/weapons/new.html.erb
<h1>New weapon</h1>

<%= render 'form' %>

<%= link_to 'Back', weapons_path(:character_id => params[:character_id]), :class => 'ajaxLink' %>

app/views/weapons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Character:</b>
  <%= @weapon.character_id %>
</p>

<p>
  <b>Title:</b>
  <%= @weapon.title %>
</p>

<p>
  <b>Description:</b>
  <%= @weapon.description %>
</p>

<p>
  <b>Damage:</b>
  <%= @weapon.damage %>
</p>

<p>
  <b>Attack bonus:</b>
  <%= @weapon.attack_bonus %>
</p>

<p>
  <b>Damage bonus:</b>
  <%= @weapon.damage_bonus %>
</p>


<%= link_to 'Edit', edit_weapon_path(@weapon), :class => 'ajaxLink' %> |
<%= link_to 'Back', weapons_path(:character_id => @weapon.character_id), :class => 'ajaxLink' %>