config/routes.rb
Dnd5::Application.routes.draw do

  resources :spells do
    collection do
      get 'list'
    end
  end

  resources :skills do
    collection do
      get 'list'
    end
  end

  resources :feats do
    collection do
      get 'list'
    end
  end

  resources :armors do
    collection do
      get 'list'
    end
  end

  resources :weapons do
    collection do
      get 'list'
    end
  end

  resources :characters

  resources :domains
  resources :classifications
  resources :races
  resources :equipment

end

app/models/armor.rb
class Armor < ActiveRecord::Base
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :title,  :description,  :cost,  :armor_bonus,  :weight,  :speed,  :don,  :remove
  has_many :characters, through: :character_armors
  ###Do not edit the above 







end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :name,  :description
  has_many :scenarios, through: :campaign_scenarios
  ###Do not edit the above 







end

app/models/character.rb
class Character < ActiveRecord::Base
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :race_id,  :class_id,  :type,  :Specialty,  :background,  :eyes,  :hair,  :height,  :weight,  :speed,  :hit_dice,  :hit_points,  :initiative,  :vision,  :size,  :level,  :strength,  :constitution,  :dexterity,  :intelligence,  :wisdom,  :charisma,  :description,  :npc
  belongs_to :classification
  belongs_to :race
  has_many :weapons, through: :character_weapons
  has_many :armors, through: :character_armors
  has_many :skills, through: :character_skills
  has_many :feats, through: :character_feats
  has_many :spells, through: :character_spells
  has_many :equipment, through: :character_equipment
  has_many :scenarios, through: :scenario_characters
  ###Do not edit the above 







end

app/models/character_armor.rb
class Character_armor < ActiveRecord::Base
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :character_id,  :armor_id,  :donned
  belongs_to :armor
  belongs_to :character
  ###Do not edit the above 







end

app/models/character_feat.rb
class Character_feat < ActiveRecord::Base
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :character_id,  :feat_id
  belongs_to :character
  belongs_to :feat
  ###Do not edit the above 







end

app/models/character_skill.rb
class Character_skill < ActiveRecord::Base
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :character_id,  :skill_id
  belongs_to :character
  belongs_to :skill
  ###Do not edit the above 







end

app/models/classification.rb
class Classification < ActiveRecord::Base
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :title,  :description
  has_many :classification_attributes
  has_many :races, through: :characters
  has_many :spells, through: :classification_spells
  ###Do not edit the above 







end

app/models/domain.rb
class Domain < ActiveRecord::Base
  validates :name, { :presence => true }
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :name,  :description
  has_many :spells
  ###Do not edit the above 







end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :title,  :cost,  :description
  has_many :characters, through: :character_equipment
  ###Do not edit the above 









end

app/models/feat.rb
class Feat < ActiveRecord::Base
  validates :title, { :presence => true }
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :title,  :description,  :prerequisites,  :benefit
  has_many :characters, through: :character_feats
  ###Do not edit the above 







end

app/models/race.rb
class Race < ActiveRecord::Base
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :title,  :description,  :npc
  has_many :race_attributes
  has_many :classifications, through: :characters
  ###Do not edit the above 







end

app/models/race_attribute.rb
class Race_attribute < ActiveRecord::Base
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :race_id,  :title,  :description
  belongs_to :race
  ###Do not edit the above 







end

app/models/scenario.rb
class Scenario < ActiveRecord::Base
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :name,  :description
  has_many :characters, through: :scenario_characters
  has_many :campaigns, through: :campaign_scenarios
  ###Do not edit the above 







end

app/models/skill.rb
class Skill < ActiveRecord::Base
  validates :title, { :presence => true }
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :title,  :description
  has_many :characters, through: :character_skills
  ###Do not edit the above 







end

app/models/spell.rb
class Spell < ActiveRecord::Base
  validates :domain_id, { :presence => true, :numericality => { :only_integer => true, :greater_than => 0 }}
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :title,  :description,  :level,  :domain_id,  :range,  :damage,  :requirement,  :effect,  :special,  :ritual
  belongs_to :domain
  has_many :characters, through: :character_spells
  has_many :classifications, through: :classification_spells
  ###Do not edit the above 







end

app/models/weapon.rb
class Weapon < ActiveRecord::Base
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :title,  :description,  :damage,  :attack_bonus,  :damage_bonus
  has_many :characters, through: :character_weapons
  ###Do not edit the above 







end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  # GET /characters
  # GET /characters.json
  def index
    @characters = Characters.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @characters }
    end
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
    @character = Characters.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @character }
    end
  end

  # GET /characters/new
  # GET /characters/new.json
  def new
    @character = Characters.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @character }
    end
  end

  # GET /characters/1/edit
  def edit
    @character = Characters.find(params[:id])
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Characters.new(params[:character])

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Characters.was successfully created.' }
        format.json { render json: @character, status: :created, location: @character }
      else
        format.html { render action: "new" }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /characters/1
  # PUT /characters/1.json
  def update
    @character = Characters.find(params[:id])

    respond_to do |format|
      if @character.update_attributes(params[:character])
        format.html { redirect_to @character, notice: 'Characters.was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character = Characters.find(params[:id])
    @character.destroy

    respond_to do |format|
      format.html { redirect_to characters_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/armors_helper.rb
module ArmorsHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/feats_helper.rb
module FeatsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/spells_helper.rb
module SpellsHelper
end

app/helpers/weapons_helper.rb
module WeaponsHelper
end

app/views/characters/_form.html.erb
<%= form_for(@character) do |f| %>
  <% if @character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
        <% @character.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%
    attribute = Hash.new()
    attribute['class'] = 'attribute'
    attribute['maxlength'] = 2
    attribute['max'] = 30
    attribute['min'] = 1


  %>


  <table>
    <tr>
      <td>
        <img src="/assets/dragon.svg" class="sectionSword"/>
        <b>Hit<br/>Points</b>
        <div id="hpBox"><%= f.number_field :hit_points %></div>
        <b>Armor<br/>Class</b>
        <div id="acBox"><%= f.number_field :armor_class %></div>
      </td>
      <td>
        <div class="field">
          <%= f.label :level %><br />
          <%= f.number_field :level %>
        </div>
        <div class="field">
          <%= f.label :initiative %><br />
          <%= f.number_field :initiative %>
        </div>
        <div class="field">
          <%= f.label :speed %><br />
          <%= f.number_field :speed %>
        </div>
        <div class="field">
          <%= f.label :hit_dice %><br />
          <%= f.text_field :hit_dice %>
        </div>
      </td>
      <td class="sheetSection">

        <div class="field">
          <%= f.label :name %><br />
          <%= f.text_field :name %>
        </div>
        <div class="field">
          <%= f.label :klass %><br />
          <%= f.text_field :klass %>
        </div>
        <div class="field">
          <%= f.label :race %><br />
          <%= f.text_field :race %>
        </div>
        <div class="field">
          <%= f.label :specialty %><br />
          <%= f.text_field :specialty %>
        </div>
        <div class="field">
          <%= f.label :background %><br />
          <%= f.text_field :background %>
        </div>
      </td>
      <td class="sheetSection">
        <div class="field">
          <%= f.label :eyes %><br />
          <%= f.text_field :eyes %>
        </div>
        <div class="field">
          <%= f.label :height %><br />
          <%= f.text_field :height %>
        </div>
        <div class="field">
          <%= f.label :hair %><br />
          <%= f.text_field :hair %>
        </div>
        <div class="field">
          <%= f.label :weight %><br />
          <%= f.text_field :weight %>
        </div>
        <div class="field">
          <%= f.label :vision %><br />
          <%= f.text_field :vision %>
        </div>
        <div class="field">
          <%= f.label :size %><br />
          <%= f.text_field :size %>
        </div>
      </td>
      <td>
        <div class="groupLeft">
          <label>Attribute</label>
          <div class="field">
            <label for="strength">STR</label>
          </div>
          <div class="field">
            <label for="constitution ">CON</label>
          </div>
          <div class="field">
            <label for="dexterity ">DEX</label>
          </div>
          <div class="field">
            <label for="intelligence ">INT</label>
          </div>
          <div class="field">
            <label for="wisdom ">WIS</label>
          </div>
          <div class="field">
            <label for="charisma ">CHA</label>
          </div>
        </div>
        <div class="groupLeft">
          <label>Base</label>

          <div class="field">
            <%= f.number_field :base_strength, attribute %>
          </div>
          <div class="field">
            <%= f.number_field :base_constitution, attribute %>
          </div>
          <div class="field">
            <%= f.number_field :base_dexterity, attribute %>
          </div>
          <div class="field">
            <%= f.number_field :base_intelligence, attribute %>
          </div>
          <div class="field">
            <%= f.number_field :base_wisdom, attribute %>
          </div>
          <div class="field">
            <%= f.number_field :base_charisma, attribute %>
          </div>
        </div>

        <div class="groupLeft">
          <label>Race</label>

          <div class="field">
            <%= f.number_field :race_strength, attribute %>
          </div>
          <div class="field">
            <%= f.number_field :race_constitution, attribute %>
          </div>
          <div class="field">
            <%= f.number_field :race_dexterity, attribute %>
          </div>
          <div class="field">
            <%= f.number_field :race_intelligence, attribute %>
          </div>
          <div class="field">
            <%= f.number_field :race_wisdom, attribute %>
          </div>
          <div class="field">
            <%= f.number_field :race_charisma, attribute %>
          </div>
        </div>
        <div class="groupLeft">
          <label>Class</label>
          <div class="field">
            <%= f.number_field :klass_strength, attribute %>
          </div>
          <div class="field">
            <%= f.number_field :klass_constitution, attribute %>
          </div>
          <div class="field">
            <%= f.number_field :klass_dexterity, attribute %>
          </div>
          <div class="field">
            <%= f.number_field :klass_intelligence, attribute %>
          </div>
          <div class="field">
            <%= f.number_field :klass_wisdom, attribute %>
          </div>
          <div class="field">
            <%= f.number_field :klass_charisma, attribute %>
          </div>

        </div>

      </td>
    </tr>
  </table>

  <div class="actions">
    <%= f.submit %>
  </div>
  <table>
    <tr>
      <td colspan="2" class="section">
        <div class="field">
          <%= f.label :description %><br />
          <%= f.text_area :description, {:rows => 0, :cols => 0, :class=>'largeDescriptionArea'} %>
        </div>
      </td>
    </tr>
    <tr>
      <td class="section">
        <div id="weaponHolder">
        </div>
      </td>
      <td class="section">
        <div id="armorHolder">
        </div>
      </td>
    </tr>
    <tr>
      <td colspan="2" class="section">
        <div id="featHolder">
        </div>
      </td>
    </tr>
    <tr>
      <td colspan="2" class="section">
        <div id="skillHolder">
        </div>
      </td>
    </tr>
    <tr>
      <td colspan="2" class="section">
        <div id="spellHolder">
        </div>
      </td>
    </tr>
    <tr>
      <td colspan="2" class="section">
        <div id="racialAttributeHolder">
        </div>
      </td>
    </tr>
    <tr>
      <td colspan="2" class="section">
        <div id="classAttributeHolder">
        </div>
      </td>
    </tr>
  </table>

  <div id="editHolder">
  </div>  
<% end %>

app/views/characters/edit.html.erb
<h1>Editing character</h1>
<script>
  $(document).ready(function(){
    defaultLocation();
  });

  function defaultLocation() {
    fillAjaxHolder('#weaponHolder','/weapons?character_id=<%= @character.id %>');
    fillAjaxHolder('#armorHolder','/armors?character_id=<%= @character.id %>');
    fillAjaxHolder('#featHolder','/feats?character_id=<%= @character.id %>');
    fillAjaxHolder('#skillHolder','/skills?character_id=<%= @character.id %>');
    fillAjaxHolder('#maneuverHolder','/maneuvers?character_id=<%= @character.id %>');
    fillAjaxHolder('#spellHolder','/spells?character_id=<%= @character.id %>');
    fillAjaxHolder('#racialAttributeHolder','/racial_attributes?character_id=<%= @character.id %>');
    fillAjaxHolder('#classAttributeHolder','/class_attributes?character_id=<%= @character.id %>');
  }
</script>
<%= render 'form' %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<h1>Listing characters</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Klass</th>
    <th>Race</th>
    <th>Specialty</th>
    <th>Background</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @characters.each do |character| %>
  <tr>
    <td><%= character.name %></td>
    <td><%= character.klass %></td>
    <td><%= character.race %></td>
    <td><%= character.specialty %></td>
    <td><%= character.background %></td>
    <td><%= character.description %></td>
    <td><%= link_to 'Show', character %></td>
    <td><%= link_to 'Edit', edit_character_path(character) %></td>
    <td><%= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Character', new_character_path %>

app/views/characters/new.html.erb
<h1>New character</h1>

<%= render 'form' %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<script>
  $(document).ready(function(){
    defaultLocation();
  });

  function defaultLocation() {
    fillAjaxHolder('#weaponHolder','/weapons/list?character_id=<%= @character.id %>');
    fillAjaxHolder('#armorHolder','/armors/list?character_id=<%= @character.id %>');
    fillAjaxHolder('#featHolder','/feats/list?character_id=<%= @character.id %>');
    fillAjaxHolder('#skillHolder','/skills/list?character_id=<%= @character.id %>');
    fillAjaxHolder('#maneuverHolder','/maneuvers/list?character_id=<%= @character.id %>');
    fillAjaxHolder('#spellHolder','/spells/list?character_id=<%= @character.id %>');
    fillAjaxHolder('#racialAttributeHolder','/racial_attributes/list?character_id=<%= @character.id %>');
    fillAjaxHolder('#classAttributeHolder','/class_attributes/list?character_id=<%= @character.id %>');
  }
</script>
<div class="page">
  <p id="notice"><%= notice %></p>
  <table class="displayTable">
    <tr>
      <td>
        <img src="/assets/dragon.svg" class="sectionSword"/>
        <b>Hit<br/>Points</b>
        <div id="hpBox"><%= @character.hit_points %></div>
        <b>Armor<br/>Class</b>
        <div id="acBox"><%= @character.armor_class %></div>
      </td>
      <td>
        <p>
        <b>Name:</b>
        <%= @character.name %>
        </p>

        <p>
        <b>Class:</b>
        <%= @character.klass %>
        </p>
        <p>
        <b>Level:</b>
        <%= @character.level %>
        </p>

        <p>
        <b>Race:</b>
        <%= @character.race %>
        </p>

        <p>
        <b>Specialty:</b>
        <%= @character.specialty %>
        </p>
        <p>
        <b>Background:</b>
        <%= @character.background %>
        </p>
      </td>
      <td>
        <p>
        <b>Speed:</b>
        <%= @character.speed %>
        </p>

        <p>
        <b>Hit dice:</b>
        <%= @character.hit_dice %>
        </p>

        <p>
        <b>Hit points:</b>
        <%= @character.hit_points %>
        </p>

        <p>
        <b>Initiative:</b>
        <%= @character.initiative %>
        </p>

      </td>
      <td>
        <p>
        <b>Eyes:</b>
        <%= @character.eyes %>
        </p>

        <p>
        <b>Height:</b>
        <%= @character.height %>
        </p>

        <p>
        <b>Hair:</b>
        <%= @character.hair %>
        </p>

        <p>
        <b>Weight:</b>
        <%= @character.weight %>
        </p>
        <p>
        <b>Vision:</b>
        <%= @character.vision %>
        </p>

        <p>
        <b>Size:</b>
        <%= @character.size %>
        </p>

      </td>
      <td>
        <div class="attributeColumn">
          <p>
          <b>Strength:</b>
          <%= @character.strength %>
          &nbsp;<%= get_attribute_bonus(@character.strength ) %>
          </p>

          <p>
          <b>Constitution:</b>
          <%= @character.constitution %>
          &nbsp;<%= get_attribute_bonus(@character.constitution) %>
          </p>

          <p>
          <b>Dexterity:</b>
          <%= @character.dexterity %>
          &nbsp;<%= get_attribute_bonus(@character.dexterity ) %>
          </p>

          <p>
          <b>Intelligence:</b>
          <%= @character.intelligence %>
          &nbsp;<%= get_attribute_bonus(@character.intelligence ) %>
          </p>

          <p>
          <b>Wisdom:</b>
          <%= @character.wisdom %>
          &nbsp;<%= get_attribute_bonus(@character.wisdom ) %>
          </p>

          <p>
          <b>Charisma:</b>
          <%= @character.charisma %>
          &nbsp;<%= get_attribute_bonus(@character.charisma ) %>
          </p>
        </div>
      </td>
    </tr>
  </table>
</div>

<div class="page">
  <table class="displayTable">
    <tr>
      <td colspan="2" class="section">
        <div id="descriptionHolder" ><b>Description</b>&nbsp;&nbsp;<%= @character.description %></div>
      </td>
    </tr>
    <tr>
      <td class="section">
        <div id="weaponHolder">
        </div>
      </td>
      <td class="section">
        <div id="armorHolder">
        </div>
      </td>
    </tr>
    <tr>
      <td colspan="2" class="section">
        <div id="featHolder" >
        </div>
      </td>
    </tr>
    <tr>
      <td colspan="2" class="section">
        <div id="skillHolder">
        </div>
      </td>
    </tr>
    <tr>
      <td colspan="2" class="section">
        <div id="spellHolder">
        </div>
      </td>
    </tr>
    <tr>
      <td colspan="2" class="section">
        <div id="racialAttributeHolder">
        </div>
      </td>
    </tr>
    <tr>
      <td colspan="2" class="section">
        <div id="classAttributeHolder">
        </div>

      </td>
    </tr>
  </table>
</div>
<div class="page">
  <%= link_to 'Edit', edit_character_path(@character) %> |
  <%= link_to 'Back', characters_path %>
</div>