config/routes.rb
Dnd5::Application.routes.draw do

  resources :spells do
    collection do
      get 'list'
    end
  end

  resources :skills do
    collection do
      get 'list'
    end
  end

  resources :feats do
    collection do
      get 'list'
    end
  end

  resources :armors do
    collection do
      get 'list'
    end
  end

  resources :weapons do
    collection do
      get 'list'
    end
  end

  resources :characters

  resources :domains
  resources :classifications
  resources :races
  resources :equipment

end

app/models/spell.rb
class Spell < ActiveRecord::Base
  validates :domain_id, { :presence => true, :numericality => { :only_integer => true, :greater_than => 0 }}
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :title,  :description,  :level,  :domain_id,  :range,  :damage,  :requirement,  :effect,  :special,  :ritual
  belongs_to :domain
  has_many :characters, through: :character_spells
  has_many :classifications, through: :classification_spells
  ###Do not edit the above 







end

app/controllers/spells_controller.rb
class SpellsController < ApplicationController
  # GET /spells
  # GET /spells.json
  #
  def index
    @letters = Spell.select("substr(title,0,1) AS letter" )

    if params[:letter].nil?
      if @letters.nil? || @letters.length < 1
        params[:letter] = 'A'
      else
        params[:letter] = @letters[0].letter
      end
    end

    @spells = Spell.where("title like upper(:letter)",{:letter => params[:letter] + '%'})
    respond_to do | format |
      render_index_html(format, 'Spells')    
      format.json { render json: @spells }
    end
  end

  def list
    @spells = Spell.where("character_id=?", params[:character_id])

    respond_to do |format|
      format.html { render :layout => 'sub_page_layout' if request.xhr? }# index.html.erb
      format.json { render json: @spells }
    end
  end

  # GET /spells/1
  # GET /spells/1.json
  def show
    @spell = Spell.find(params[:id])
    respond_to do |format|
      show_html(format,@spell)
      format.json { render json: @spell }
    end
  end

  # GET /spells/new
  # GET /spells/new.json
  def new    
    @spell = Spell.new
    respond_to do |format|
      new_html(format, @spell)
      format.json { render json: @spell }
    end
  end

  # GET /spells/1/edit
  def edit
    @spell = Spell.find(params[:id])
    respond_to do |format|
      edit_html(format,@spell)
      format.json { render json: @spell }
    end
  end

  # POST /spells
  # POST /spells.json
  def create
    @spell = Spell.new(params[:spell])
    respond_to do |format|
      if @spell.save
        format.html { redirect_to @spell, notice: 'Spell was successfully created.' }
        format.json { render json: @spell, status: :created, location: @spell }
      else
        new_html(format, @spell)
        format.json { render json: @spell.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /spells/1
  # PUT /spells/1.json
  def update
    @spell = Spell.find(params[:id])

    respond_to do |format|
      if @spell.update_attributes(params[:spell])
        format.html { redirect_to @spell, notice: 'Spell was successfully updated.' }
        format.json { head :no_content }
      else
        edit_html(format,@spell)
        format.json { render json: @spell.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spells/1
  # DELETE /spells/1.json
  def destroy
    @spell = Spell.find(params[:id])
    @spell.destroy

    respond_to do |format|
      format.html { redirect_to spells_url }
      format.json { head :no_content }
    end
  end

  protected
  def new_html(format, model)
    render_new_html(format, model, 'New Spell')
  end

  def edit_html(format, model)
    render_edit_html(format, model, 'Spell')
  end 

  def show_html(format, model)
    render_show_html(format, model, 'Spell')
  end  
end

app/helpers/spells_helper.rb
module SpellsHelper
end

app/views/spells/_form.html.erb
<%= form_for(@spell) do |f| %>
  <% if @spell.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spell.errors.count, "error") %> prohibited this spell from being saved:</h2>

      <ul>
      <% @spell.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :level %><br />
    <%= f.number_field :level %>
  </div>
  <div class="field">
    <%= f.label 'Domain' %><br />
    <%= f.collection_select(:domain_id, Domain.all, :id, :name, prompt: true) %>
  </div>
  <div class="field">
    <%= f.label :range %><br />
    <%= f.text_field :range %>
  </div>
  <div class="field">
    <%= f.label :damage %><br />
    <%= f.text_field :damage %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, {:rows=>0, :cols=>0, :class => 'smallDescriptionArea' }%>
  </div>
  <div class="field">
    <%= f.label :requirement %><br />
    <%= f.text_area :requirement , {:rows=>0, :cols=>0, :class => 'smallDescriptionArea' }%>
  </div>
  <div class="field">
    <%= f.label :effect %><br />
    <%= f.text_area :effect, {:rows=>0, :cols=>0, :class => 'smallDescriptionArea' }%>
  </div>
  <div class="field">
    <%= f.label :special %><br />
    <%= f.text_area :special, {:rows=>0, :cols=>0, :class => 'smallDescriptionArea' }%>
  </div>
  <div class="field">
    <%= f.label :ritual %><br />
    <%= f.check_box :ritual %>
  </div>
  <div class="actions">
    <%= f.submit nil, :class => 'ajaxSubmit' %>
  </div>
<% end %>

app/views/spells/_index.html.erb
<table>
  <tr>
    <th>Title</th>
    <th>Level</th>
    <th>Type</th>
    <th>Range</th>
    <th>Damage</th>
    <th>Ritual</th>
    <th>Prepared</th>        
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @spells.each do |spell| %>
  <tr>
    <td><%= spell.title %></td>
    <td><%= spell.level %></td>
    <td><%= spell.domain.name %></td>
    <td><%= spell.range %></td>
    <td><%= spell.damage %></td>
    <td><%= spell.ritual %></td>
    <td></td>
    <td><%= link_to 'Show', spell, :class => 'ajaxLink'  %></td>
    <td><%= link_to 'Edit', edit_spell_path(spell), :class => 'ajaxLink' %></td>
    <td><%= link_to 'Destroy', spell_path(spell), :class => 'ajaxDeleteLink' %></td>

  </tr>
<% end %>
</table>

app/views/spells/_show.html.erb
<p>
  <b>Title:</b>
  <%= @spell.title %>
</p>

<p>
  <b>Level:</b>
  <%= @spell.level %>
</p>

<p>
  <b>Domain:</b>
  <%= @spell.domain.name %>
</p>

<p>
  <b>Range:</b>
  <%= @spell.range %>
</p>

<p>
  <b>Damage:</b>
  <%= @spell.damage %>
</p>

<p>
  <b>Description:</b>
  <%= @spell.description %>
</p>

<p>
  <b>Requirement:</b>
  <%= @spell.requirement %>
</p>

<p>
  <b>Effect:</b>
  <%= @spell.effect %>
</p>

<p>
  <b>Special:</b>
  <%= @spell.special %>
</p>

<p>
  <b>Ritual:</b>
  <%= @spell.ritual %>
</p>

<p>
  <b>Prepared:</b>
</p>

app/views/spells/list.html.erb
<h3>Spells
 <img src="/assets/Sword-Left.svg" class="sectionSword"/></h3>

<table>
  <tr>
    <th>Title</th>
    <th>Level</th>
    <th>Type</th>
    <th>Range</th>
    <th>Damage</th>
    <th>Ritual</th>
    <th>Prepared</th>
  </tr>

<% @spells.each do |spell| %>
  <tr>
    <td><%= spell.title %></td>
    <td><%= spell.level %></td>
    <td><%= spell.domain %></td>
    <td><%= spell.range %></td>
    <td><%= spell.damage %></td>
    <td><%= spell.ritual %></td>
    <td><%= spell.prepared %></td>

  </tr>
  <tr>
    <td colspan="7" class="goLeft"><b>Description:</b><%= spell.description %></td>
  </tr>
  <tr>
    <td colspan="7" class="goLeft"><b>Effect:</b><%= spell.effect %><hr/></td>
  </tr>
<% end %>
</table>