config/routes.rb
Dnd5::Application.routes.draw do

  resources :spells do
    collection do
      get 'list'
    end
  end

  resources :skills do
    collection do
      get 'list'
    end
  end

  resources :feats do
    collection do
      get 'list'
    end
  end

  resources :armors do
    collection do
      get 'list'
    end
  end

  resources :weapons do
    collection do
      get 'list'
    end
  end

  resources :characters

  resources :domains
  resources :classifications
  resources :races
  resources :equipment

end

app/models/armor.rb
class Armor < ActiveRecord::Base
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :title,  :description,  :cost,  :armor_bonus,  :weight,  :speed,  :don,  :remove
  has_many :characters, through: :character_armors
  ###Do not edit the above 







end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :name,  :description
  has_many :scenarios, through: :campaign_scenarios
  ###Do not edit the above 







end

app/models/character.rb
class Character < ActiveRecord::Base
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :race_id,  :class_id,  :type,  :Specialty,  :background,  :eyes,  :hair,  :height,  :weight,  :speed,  :hit_dice,  :hit_points,  :initiative,  :vision,  :size,  :level,  :strength,  :constitution,  :dexterity,  :intelligence,  :wisdom,  :charisma,  :description,  :npc
  belongs_to :classification
  belongs_to :race
  has_many :weapons, through: :character_weapons
  has_many :armors, through: :character_armors
  has_many :skills, through: :character_skills
  has_many :feats, through: :character_feats
  has_many :spells, through: :character_spells
  has_many :equipment, through: :character_equipment
  has_many :scenarios, through: :scenario_characters
  ###Do not edit the above 







end

app/models/character_armor.rb
class Character_armor < ActiveRecord::Base
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :character_id,  :armor_id,  :donned
  belongs_to :armor
  belongs_to :character
  ###Do not edit the above 







end

app/models/character_feat.rb
class Character_feat < ActiveRecord::Base
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :character_id,  :feat_id
  belongs_to :character
  belongs_to :feat
  ###Do not edit the above 







end

app/models/character_skill.rb
class Character_skill < ActiveRecord::Base
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :character_id,  :skill_id
  belongs_to :character
  belongs_to :skill
  ###Do not edit the above 







end

app/models/character_spell.rb
class Character_spell < ActiveRecord::Base
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :character_id,  :spell_id,  :prepared
  belongs_to :character
  belongs_to :spell
  ###Do not edit the above 







end

app/models/classification.rb
class Classification < ActiveRecord::Base
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :title,  :description
  has_many :classification_attributes
  has_many :races, through: :characters
  has_many :spells, through: :classification_spells
  ###Do not edit the above 







end

app/models/domain.rb
class Domain < ActiveRecord::Base
  validates :name, { :presence => true }
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :name,  :description
  has_many :spells
  ###Do not edit the above 







end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :title,  :cost,  :description
  has_many :characters, through: :character_equipment
  ###Do not edit the above 









end

app/models/feat.rb
class Feat < ActiveRecord::Base
  validates :title, { :presence => true }
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :title,  :description,  :prerequisites,  :benefit
  has_many :characters, through: :character_feats
  ###Do not edit the above 







end

app/models/race.rb
class Race < ActiveRecord::Base
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :title,  :description,  :npc
  has_many :race_attributes
  has_many :classifications, through: :characters
  ###Do not edit the above 







end

app/models/race_attribute.rb
class Race_attribute < ActiveRecord::Base
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :race_id,  :title,  :description
  belongs_to :race
  ###Do not edit the above 







end

app/models/scenario.rb
class Scenario < ActiveRecord::Base
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :name,  :description
  has_many :characters, through: :scenario_characters
  has_many :campaigns, through: :campaign_scenarios
  ###Do not edit the above 







end

app/models/skill.rb
class Skill < ActiveRecord::Base
  validates :title, { :presence => true }
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :title,  :description
  has_many :characters, through: :character_skills
  ###Do not edit the above 







end

app/models/spell.rb
class Spell < ActiveRecord::Base
  validates :domain_id, { :presence => true, :numericality => { :only_integer => true, :greater_than => 0 }}
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :title,  :description,  :level,  :domain_id,  :range,  :damage,  :requirement,  :effect,  :special,  :ritual
  belongs_to :domain
  has_many :characters, through: :character_spells
  has_many :classifications, through: :classification_spells
  ###Do not edit the above 







end

app/models/weapon.rb
class Weapon < ActiveRecord::Base
  ###Do not edit the below 
  ###Begin RDiaTool Code 
  attr_accessible  :title,  :description,  :damage,  :attack_bonus,  :damage_bonus
  has_many :characters, through: :character_weapons
  ###Do not edit the above 







end

app/controllers/armors_controller.rb
class ArmorsController < ApplicationController
  # GET /armors
  # GET /armors.json
  def index

    @armors = Armor.where("character_id=?", params[:character_id])
    respond_to do |format|
      format.html  { render :layout => 'sub_page_layout' if request.xhr? } # index.html.erb
      format.json { render json: @armors }
    end
  end

  def list 
    @armors = Armor.where("character_id=?", params[:character_id])

    respond_to do |format|
      format.html { render :layout => 'sub_page_layout' if request.xhr? } # index.html.erb
      format.json { render json: @armors }
    end
  end

  # GET /armors/1
  # GET /armors/1.json
  def show
    @armor = Armor.find(params[:id])

    respond_to do |format|
      format.html  { render :layout => 'sub_page_layout' if request.xhr? }  # show.html.erb
      format.json { render json: @armor }
    end
  end

  # GET /armors/new
  # GET /armors/new.json
  def new
    @armor = Armor.new
    @armor.character_id=params[:character_id]

    respond_to do |format|
      format.html  { render :layout => 'sub_page_layout' if request.xhr? }  # new.html.erb
      format.json { render json: @armor }
    end
  end

  # GET /armors/1/edit
  def edit
    @armor = Armor.find(params[:id])
  end

  # POST /armors
  # POST /armors.json
  def create
    @armor = Armor.new(params[:armor])

    respond_to do |format|
      if @armor.save
        format.html { redirect_to @armor, notice: 'Armor was successfully created.' }
        format.json { render json: @armor, status: :created, location: @armor }
      else
        format.html { render action: "new" }
        format.json { render json: @armor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /armors/1
  # PUT /armors/1.json
  def update
    @armor = Armor.find(params[:id])

    respond_to do |format|
      if @armor.update_attributes(params[:armor])
        format.html { redirect_to @armor, notice: 'Armor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @armor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /armors/1
  # DELETE /armors/1.json
  def destroy
    @armor = Armor.find(params[:id])
    @armor.destroy

    respond_to do |format|
      format.html { redirect_to armors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/armors_helper.rb
module ArmorsHelper
end

app/helpers/feats_helper.rb
module FeatsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/spells_helper.rb
module SpellsHelper
end

app/helpers/weapons_helper.rb
module WeaponsHelper
end

app/views/armors/_ajax_links.html.erb
<script>
  ajaxifyLink('.ajaxArmorLink','#armorHolder')
  ajaxifyDeleteLink('.ajaxArmorDeleteLink','#armorHolder')
  ajaxifySubmit('.ajaxArmorSubmit','#armorHolder')
</script>

app/views/armors/_form.html.erb
<%= form_for(@armor) do |f| %>
  <% if @armor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@armor.errors.count, "error") %> prohibited this armor from being saved:</h2>

      <ul>
      <% @armor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div><%= render '/layouts/ajaxify_links' %>
  <% end %>

  <div class="field">
    <%= f.hidden_field :character_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, {:rows=>0, :cols=>0, :class => 'smallDescriptionArea' }%>
  </div>
  <div class="field">
    <%= f.label :armor_bonus %><br />
    <%= f.number_field :armor_bonus %>
  </div>
  <div class="field">
    <%= f.label :cost %><br />
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label :speed %><br />
    <%= f.number_field :speed %>
  </div>
  <div class="field">
    <%= f.label :don %><br />
    <%= f.number_field :don %>
  </div>
  <div class="field">
    <%= f.label :remove %><br />
    <%= f.number_field :remove %>
  </div>
  <div class="actions">
    <%= f.submit nil, :class => 'ajaxArmorSubmit' %>
  </div>
<% end %>

app/views/armors/edit.html.erb
<h1>Editing armor</h1>

<%= render 'form' %>

<%= link_to 'Show', @armor, :class => 'ajaxLink' %> |
<%= link_to 'Back', armors_path(:character_id => @armor.character_id), :class => 'ajaxLink' %>
<%= render '/layouts/ajaxify_links' %>

app/views/armors/index.html.erb
<h1>Listing armors</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Armor<br/> bonus</th>
    <th>Weight</th>
    <th>Speed</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @armors.each do |armor| %>
  <tr>
    <td><%= armor.title %></td>
    <td><%= armor.armor_bonus %></td>
    <td><%= armor.weight %></td>
    <td><%= armor.speed %></td>
    <td><%= link_to 'Show', armor, :class => 'ajaxLink'  %></td>
    <td><%= link_to 'Edit', edit_armor_path(armor), :class => 'ajaxLink' %></td>
    <td><%= link_to 'Destroy', armor_path(armor,:character_id => armor.character_id), :class => 'ajaxArmorDeleteLink' %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Armor', new_armor_path(:character_id => params[:character_id]), :class => 'ajaxArmorLink' %>
<%= render '/layouts/ajaxify_links' %>

app/views/armors/list.html.erb
<h3>Armors
 <img src="/assets/Sword-Right.svg" class="sectionSword"/></h3>

<table>
  <tr>
    <th>Title</th>
    <th>Armor<br/> bonus</th>
    <th>Weight</th>
    <th>Speed</th>
  </tr>

<% @armors.each do |armor| %>
  <tr>
    <td><%= armor.title %></td>
    <td><%= armor.armor_bonus %></td>
    <td><%= armor.weight %></td>
    <td><%= armor.speed %></td>
  </tr>
<% end %>
</table>

app/views/armors/new.html.erb
<h1>New armor</h1>

<%= render 'form' %>

<%= link_to 'Back', armors_path(:character_id => params[:character_id]), :class => 'ajaxArmorLink' %>
<%= render '/layouts/ajaxify_links' %>

app/views/armors/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <b>Title:</b>
  <%= @armor.title %>
</p>

<p>
  <b>Description:</b>
  <%= @armor.description %>
</p>

<p>
  <b>Armor bonus:</b>
  <%= @armor.armor_bonus %>
</p>

<p>
  <b>Cost:</b>
  <%= @armor.cost %>
</p>

<p>
  <b>Weight:</b>
  <%= @armor.weight %>
</p>

<p>
  <b>Speed:</b>
  <%= @armor.speed %>
</p>

<p>
  <b>Don:</b>
  <%= @armor.don %>
</p>

<p>
  <b>Remove:</b>
  <%= @armor.remove %>
</p>

<%= link_to 'Edit', edit_armor_path(@armor), :class => 'ajaxLink' %> |
<%= link_to 'Back', armors_path(:character_id => @armor.character_id), :class => 'ajaxLink' %>
<%= render '/layouts/ajaxify_links' %>